apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
spec:
  template:
    spec:
      containers:
        - name: catalogue
          image: robotshop/rs-catalogue:latest
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
