apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
spec:
  template:
    spec:
      containers:
        - name: dispatch
          image: robotshop/rs-dispatch:latest
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
