apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb
          image: robotshop/rs-mongodb:latest
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
