apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-redis
