apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
  labels:
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      name: mysql
      labels:
        service: mysql
    spec:
      containers:
      - name: mysql
        image: IMAGE_BLOCKER
        ports:
          - containerPort: 3306
        resources:
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    service: mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    service: mysql
