apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
    stage: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      containers:
      - name: payment
        image: IMAGE_BLOCKER
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: CPU
            memory: MEM
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment
