apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: IMAGE_BLOCKER
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            requests:
              cpu: CPU_REQ
              memory: MEM_REQ
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  ports:
    - name: tcp-amqp
      port: 5672
      targetPort: 5672
    - name: http-management
      port: 15672
      targetPort: 15672
  selector:
    service: rabbitmq
            
