apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      name: redis
      labels: 
        service: redis
    spec:
      containers:
        - name: redis
          image: redis:4.0.6
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /mnt/redis
          resources:
            requests:
              cpu: 100Mi
              memory: 50Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-pvc    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    service: redis
