apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    service: user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
      - name: user
        image: IMAGE
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: CPU
            memory: MEM
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    service: user
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: user
