apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  template:
    spec:
      containers:
        - name: payment
          image: robotshop/rs-payment:latest
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
