apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7-management-alpine
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
