apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  template:
    spec:
      containers:
        - name: ratings
          image: robotshop/rs-ratings:latest
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
