apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          image: robotshop/rs-web:latest
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
